services:
  nginx:
    container_name: nginx
    image: nginx:69
    restart: on-failure
    build: ./requirements/nginx
#    depends_on:
#      - wordpress
    networks:
      - inception
    ports:
      - 443:443
    env_file:
      - .env


  mariadb:
    container_name: mariadb
    image: mariadb:69
    restart: on-failure
    build: ./requirements/mariadb
    networks:
      - inception
    ports:
      - 3306:3306
    env_file:
      - .env

networks:
  inception:
    name: inception
    driver: bridge
