services:
  nginx:
    container_name: nginx
    restart: always
    build: ./requirements/nginx
    depends_on:
      - wordpress
    networks:
      - inception
    ports:
      - 443:443

  wordpress:
    container_name: wordpress
    restart: always
    build: ./requirements/wordpress
    depends_on:
      mariadb:
        condition : service_healthy

    networks:
      - inception
    env_file:
      - .env

  mariadb:
    container_name: mariadb
    restart: always
    build: ./requirements/mariadb
    networks:
      - inception
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "nc", "-zv", "mariadb", "3306"]
      interval: 1s
      timeout: 5s
      retries: 10

networks:
  inception:
    name: inception
    driver: bridge
