services:
  nginx:
    container_name: nginx
    image: nginx:69
    restart: always
    build: ./requirements/nginx
    depends_on:
      - wordpress
    networks:
      - inception
    ports:
      - 443:443
    volumes:
      - ./data/wordpress:/var/www/html

  wordpress:
    container_name: wordpress
    image: wordpress:69
    restart: always
    build: ./requirements/wordpress
    depends_on:
      mariadb:
        condition : service_healthy
    volumes:
      - ./data/wordpress:/var/www/html

    networks:
      - inception
    env_file:
      - .env

  mariadb:
    container_name: mariadb
    image: mariadb:69
    restart: always
    build: ./requirements/mariadb
    networks:
      - inception
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "nc", "-zv", "mariadb", "3306"]
      interval: 2s
      timeout: 5s
      retries: 20

networks:
  inception:
    name: inception
    driver: bridge
